### ISSUE TITLE
errors when pushing: socket hang up

### ISSUE THREAD

**Issue by ynux** [muc-fluechtlingsrat/elastify-eurostat#6]
https://github.com/elastic/elasticsearch-js/issues/521

    Elasticsearch ERROR: 2017-09-17T08:28:53Z
      Error: Request error, retrying
      POST https://8990fc13a3196a888617a06899c0bc8b.eu-west-1.aws.found.io:9243/asylum_appl_annual_full/full_migr_asyappctza/_bulk => socket hang up
          at Log.error (/Users/suny/elastify-eurostat/node_modules/elasticsearch/src/lib/log.js:225:56)
          at checkRespForFailure (/Users/suny/elastify-eurostat/node_modules/elasticsearch/src/lib/transport.js:258:18)
          at HttpConnector.<anonymous> (/Users/suny/elastify-eurostat/node_modules/elasticsearch/src/lib/connectors/http.js:157:7)
          at ClientRequest.bound (/Users/suny/elastify-eurostat/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)
          at emitOne (events.js:115:13)
          at ClientRequest.emit (events.js:210:7)
          at TLSSocket.socketCloseListener (_http_client.js:377:9)
          at emitOne (events.js:120:20)
          at TLSSocket.emit (events.js:210:7)
          at _handle.close (net.js:549:12)

**Comment by ynux** [comment]
Also this, which may be related (https://github.com/elastic/elasticsearch-js/issues/508):

Elasticsearch ERROR: 2017-09-17T08:48:42Z
  Error: Request error, retrying
  POST https://8990fc13a3196a888617a06899c0bc8b.eu-west-1.aws.found.io:9243/asylum_appl_annual_full/full_migr_asyappctza/_bulk => write EPIPE
      at Log.error (/Users/suny/elastify-eurostat/node_modules/elasticsearch/src/lib/log.js:225:56)
      at checkRespForFailure (/Users/suny/elastify-eurostat/node_modules/elasticsearch/src/lib/transport.js:258:18)
      at HttpConnector.<anonymous> (/Users/suny/elastify-eurostat/node_modules/elasticsearch/src/lib/connectors/http.js:157:7)
      at ClientRequest.bound (/Users/suny/elastify-eurostat/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)
      at emitOne (events.js:115:13)
      at ClientRequest.emit (events.js:210:7)
      at TLSSocket.socketErrorListener (_http_client.js:401:9)
      at emitOne (events.js:115:13)
      at TLSSocket.emit (events.js:210:7)
      at onwriteError (_stream_writable.js:392:12)
